server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/stocktracker
    redis:
      host: redis
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 86400

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

stock:
  client:
    brapi:
      active: false
      url: https://brapi.dev/api/quote
      token: 'seu-token-aqui'

security:
  secretLoginKey: "a-minha-chave-secreta"
